// Mock Data Store for MindCare Application

// Users
export const mockUsers = [
  { id: 1, username: 'admin@mindcare.com', email: 'admin@mindcare.com', password: 'admin123', firstName: 'Sarah', lastName: 'Mitchell', role: 'ADMIN', isActive: true, createdDate: '2024-01-15', lastLogin: '2025-07-11T08:30:00', phone: '555-123-4567' },
  { id: 2, username: 'psychiatrist@mindcare.com', email: 'psychiatrist@mindcare.com', password: 'psychiatrist123', firstName: 'James', lastName: 'Rodriguez', role: 'PSYCHIATRIST', licenseType: 'MD', licenseNumber: 'MD-78901', licenseState: 'California', licenseExpiry: '2027-06-30', specialties: ['Psychopharmacology', 'Mood Disorders', 'Anxiety Disorders'], isActive: true, createdDate: '2024-02-01', lastLogin: '2025-07-11T09:15:00' },
  { id: 3, username: 'psychologist@mindcare.com', email: 'psychologist@mindcare.com', password: 'psychologist123', firstName: 'Emily', lastName: 'Chen', role: 'PSYCHOLOGIST', licenseType: 'PsyD', licenseNumber: 'PSY-34567', licenseState: 'New York', specialties: ['CBT', 'Neuropsychology', 'PTSD'], isActive: true },
  { id: 4, username: 'therapist@mindcare.com', email: 'therapist@mindcare.com', password: 'therapist123', firstName: 'Michael', lastName: 'Thompson', role: 'THERAPIST', licenseType: 'LCSW', licenseNumber: 'LCSW-23456', licenseState: 'California', specialties: ['CBT', 'DBT', 'Trauma-Focused', 'Family Systems'], isActive: true },
  { id: 5, username: 'supervisor@mindcare.com', email: 'supervisor@mindcare.com', password: 'supervisor123', firstName: 'Patricia', lastName: 'Williams', role: 'SUPERVISOR', licenseType: 'LMFT', licenseNumber: 'LMFT-45678', licenseState: 'California', supervisees: [4], isActive: true },
  { id: 6, username: 'case_manager@mindcare.com', email: 'case_manager@mindcare.com', password: 'case123', firstName: 'Robert', lastName: 'Davis', role: 'CASE_MANAGER', isActive: true },
  { id: 7, username: 'receptionist@mindcare.com', email: 'receptionist@mindcare.com', password: 'receptionist123', firstName: 'Jennifer', lastName: 'Adams', role: 'RECEPTIONIST', isActive: true },
  { id: 8, username: 'client@mindcare.com', email: 'client@mindcare.com', password: 'client123', firstName: 'Alex', lastName: 'Morgan', role: 'CLIENT', isActive: true },
  { id: 9, username: 'counselor@mindcare.com', email: 'counselor@mindcare.com', password: 'counselor123', firstName: 'Daniel', lastName: 'Lee', role: 'COUNSELOR', isActive: true }
];

// Clients
export const mockClients = [
  {
    "id": 101,
    "clientNumber": "MC-2023-10-001",
    "firstName": "Sophia",
    "lastName": "Davis",
    "dateOfBirth": "1965-11-25",
    "gender": "Female",
    "phone": "555-259-8953",
    "email": "sophia.davis@example.com",
    "emergencyContactName": "Marcus Davis",
    "emergencyContactPhone": "555-423-7856",
    "insuranceProvider": "Cigna",
    "status": "DISCHARGED",
    "assignedTherapistId": 2,
    "intakeDate": "2023-10-12",
    "isMinor": false,
    "presentingConcerns": "Client reports symptoms related to post-traumatic stress disorder, unspecified. Also experiencing difficulties sleeping and concentrating.",
    "diagnosisPrimary": "F43.10",
    "diagnosisSecondary": "F43.22"
  },
  {
    "id": 102,
    "clientNumber": "MC-2025-04-002",
    "firstName": "Ava",
    "lastName": "Johnson",
    "dateOfBirth": "1988-02-02",
    "gender": "Female",
    "phone": "555-879-6307",
    "email": "ava.johnson@example.com",
    "emergencyContactName": "William Johnson",
    "emergencyContactPhone": "555-969-4202",
    "insuranceProvider": "Medicare",
    "status": "WAITLIST",
    "assignedTherapistId": null,
    "intakeDate": "2025-04-15",
    "isMinor": false,
    "presentingConcerns": "Client reports symptoms related to generalized anxiety disorder. ",
    "diagnosisPrimary": "F41.1",
    "diagnosisSecondary": null
  },
  {
    "id": 103,
    "clientNumber": "MC-2025-06-003",
    "firstName": "Jennifer",
    "lastName": "Miller",
    "dateOfBirth": "1966-03-18",
    "gender": "Female",
    "phone": "555-845-2907",
    "email": "jennifer.miller@example.com",
    "emergencyContactName": "Richard Miller",
    "emergencyContactPhone": "555-785-9254",
    "insuranceProvider": "Kaiser Permanente",
    "status": "ACTIVE",
    "assignedTherapistId": 2,
    "intakeDate": "2025-06-29",
    "isMinor": false,
    "presentingConcerns": "Client reports symptoms related to bipolar disorder, current episode depressed, moderate. ",
    "diagnosisPrimary": "F31.32",
    "diagnosisSecondary": "F32.1"
  },
  {
    "id": 104,
    "clientNumber": "MC-2023-01-004",
    "firstName": "Marcus",
    "lastName": "Rodriguez",
    "dateOfBirth": "1952-07-21",
    "gender": "Male",
    "phone": "555-431-4309",
    "email": "marcus.rodriguez@example.com",
    "emergencyContactName": "William Rodriguez",
    "emergencyContactPhone": "555-508-1762",
    "insuranceProvider": "Cigna",
    "status": "ACTIVE",
    "assignedTherapistId": 4,
    "intakeDate": "2023-01-17",
    "isMinor": false,
    "presentingConcerns": "Client reports symptoms related to post-traumatic stress disorder, unspecified. Also experiencing difficulties sleeping and concentrating.",
    "diagnosisPrimary": "F43.10",
    "diagnosisSecondary": "F31.32"
  },
  {
    "id": 105,
    "clientNumber": "MC-2023-06-005",
    "firstName": "Morgan",
    "lastName": "Davis",
    "dateOfBirth": "1967-12-14",
    "gender": "Male",
    "phone": "555-310-2176",
    "email": "morgan.davis@example.com",
    "emergencyContactName": "John Davis",
    "emergencyContactPhone": "555-164-6668",
    "insuranceProvider": "UnitedHealthcare",
    "status": "ACTIVE",
    "assignedTherapistId": 2,
    "intakeDate": "2023-06-19",
    "isMinor": false,
    "presentingConcerns": "Client reports symptoms related to bipolar disorder, current episode depressed, moderate. Also experiencing difficulties sleeping and concentrating.",
    "diagnosisPrimary": "F31.32",
    "diagnosisSecondary": "F31.32"
  },
  {
    "id": 106,
    "clientNumber": "MC-2023-08-006",
    "firstName": "Jordan",
    "lastName": "Williams",
    "dateOfBirth": "2010-05-28",
    "gender": "Male",
    "phone": "555-578-3234",
    "email": "jordan.williams@example.com",
    "emergencyContactName": "Morgan Williams",
    "emergencyContactPhone": "555-615-3111",
    "insuranceProvider": "Self-Pay",
    "status": "WAITLIST",
    "assignedTherapistId": null,
    "intakeDate": "2023-08-10",
    "isMinor": true,
    "presentingConcerns": "Client reports symptoms related to post-traumatic stress disorder, unspecified. ",
    "diagnosisPrimary": "F43.10",
    "diagnosisSecondary": "F32.1"
  },
  {
    "id": 107,
    "clientNumber": "MC-2023-11-007",
    "firstName": "Richard",
    "lastName": "Rodriguez",
    "dateOfBirth": "1967-04-12",
    "gender": "Male",
    "phone": "555-861-1744",
    "email": "richard.rodriguez@example.com",
    "emergencyContactName": "Alex Rodriguez",
    "emergencyContactPhone": "555-655-3922",
    "insuranceProvider": "Aetna",
    "status": "ACTIVE",
    "assignedTherapistId": 2,
    "intakeDate": "2023-11-13",
    "isMinor": false,
    "presentingConcerns": "Client reports symptoms related to post-traumatic stress disorder, unspecified. ",
    "diagnosisPrimary": "F43.10",
    "diagnosisSecondary": "F41.1"
  },
  {
    "id": 108,
    "clientNumber": "MC-2025-06-008",
    "firstName": "John",
    "lastName": "Jones",
    "dateOfBirth": "1991-06-01",
    "gender": "Male",
    "phone": "555-150-3359",
    "email": "john.jones@example.com",
    "emergencyContactName": "Charles Jones",
    "emergencyContactPhone": "555-907-3121",
    "insuranceProvider": "Medicare",
    "status": "INQUIRY",
    "assignedTherapistId": null,
    "intakeDate": "2025-06-13",
    "isMinor": false,
    "presentingConcerns": "Client reports symptoms related to adjustment disorder with anxiety. Also experiencing difficulties sleeping and concentrating.",
    "diagnosisPrimary": "F43.22",
    "diagnosisSecondary": null
  },
  {
    "id": 109,
    "clientNumber": "MC-2024-05-009",
    "firstName": "Sarah",
    "lastName": "Miller",
    "dateOfBirth": "1958-01-27",
    "gender": "Female",
    "phone": "555-103-6128",
    "email": "sarah.miller@example.com",
    "emergencyContactName": "Richard Miller",
    "emergencyContactPhone": "555-521-5109",
    "insuranceProvider": "Self-Pay",
    "status": "INQUIRY",
    "assignedTherapistId": null,
    "intakeDate": "2024-05-05",
    "isMinor": false,
    "presentingConcerns": "Client reports symptoms related to social phobia, unspecified. Also experiencing difficulties sleeping and concentrating.",
    "diagnosisPrimary": "F40.10",
    "diagnosisSecondary": null
  },
  {
    "id": 110,
    "clientNumber": "MC-2025-03-010",
    "firstName": "Karen",
    "lastName": "Gonzalez",
    "dateOfBirth": "1993-05-03",
    "gender": "Female",
    "phone": "555-376-9508",
    "email": "karen.gonzalez@example.com",
    "emergencyContactName": "William Gonzalez",
    "emergencyContactPhone": "555-951-4583",
    "insuranceProvider": "Kaiser Permanente",
    "status": "ACTIVE",
    "assignedTherapistId": 4,
    "intakeDate": "2025-03-16",
    "isMinor": false,
    "presentingConcerns": "Client reports symptoms related to post-traumatic stress disorder, unspecified. Also experiencing difficulties sleeping and concentrating.",
    "diagnosisPrimary": "F43.10",
    "diagnosisSecondary": "F32.1"
  },
  {
    "id": 111,
    "clientNumber": "MC-2023-08-011",
    "firstName": "Taylor",
    "lastName": "Miller",
    "dateOfBirth": "1995-07-26",
    "gender": "Male",
    "phone": "555-665-2419",
    "email": "taylor.miller@example.com",
    "emergencyContactName": "James Miller",
    "emergencyContactPhone": "555-485-1914",
    "insuranceProvider": "Kaiser Permanente",
    "status": "ACTIVE",
    "assignedTherapistId": 2,
    "intakeDate": "2023-08-27",
    "isMinor": false,
    "presentingConcerns": "Client reports symptoms related to attention-deficit hyperactivity disorder, predominantly inattentive type. Also experiencing difficulties sleeping and concentrating.",
    "diagnosisPrimary": "F90.0",
    "diagnosisSecondary": null
  },
  {
    "id": 112,
    "clientNumber": "MC-2024-12-012",
    "firstName": "Joseph",
    "lastName": "Hernandez",
    "dateOfBirth": "1950-10-11",
    "gender": "Male",
    "phone": "555-791-3901",
    "email": "joseph.hernandez@example.com",
    "emergencyContactName": "David Hernandez",
    "emergencyContactPhone": "555-852-1357",
    "insuranceProvider": "Self-Pay",
    "status": "INACTIVE",
    "assignedTherapistId": 4,
    "intakeDate": "2024-12-17",
    "isMinor": false,
    "presentingConcerns": "Client reports symptoms related to attention-deficit hyperactivity disorder, predominantly inattentive type. ",
    "diagnosisPrimary": "F90.0",
    "diagnosisSecondary": null
  },
  {
    "id": 113,
    "clientNumber": "MC-2025-04-013",
    "firstName": "Thomas",
    "lastName": "Williams",
    "dateOfBirth": "1972-07-11",
    "gender": "Male",
    "phone": "555-969-3319",
    "email": "thomas.williams@example.com",
    "emergencyContactName": "Joseph Williams",
    "emergencyContactPhone": "555-798-6043",
    "insuranceProvider": "Aetna",
    "status": "ACTIVE",
    "assignedTherapistId": 4,
    "intakeDate": "2025-04-23",
    "isMinor": false,
    "presentingConcerns": "Client reports symptoms related to post-traumatic stress disorder, unspecified. Also experiencing difficulties sleeping and concentrating.",
    "diagnosisPrimary": "F43.10",
    "diagnosisSecondary": "F40.10"
  },
  {
    "id": 114,
    "clientNumber": "MC-2025-04-014",
    "firstName": "Jennifer",
    "lastName": "Anderson",
    "dateOfBirth": "1980-01-18",
    "gender": "Female",
    "phone": "555-836-9124",
    "email": "jennifer.anderson@example.com",
    "emergencyContactName": "Charles Anderson",
    "emergencyContactPhone": "555-255-7323",
    "insuranceProvider": "Medicare",
    "status": "DISCHARGED",
    "assignedTherapistId": 4,
    "intakeDate": "2025-04-03",
    "isMinor": false,
    "presentingConcerns": "Client reports symptoms related to post-traumatic stress disorder, unspecified. ",
    "diagnosisPrimary": "F43.10",
    "diagnosisSecondary": null
  },
  {
    "id": 115,
    "clientNumber": "MC-2025-05-015",
    "firstName": "Sarah",
    "lastName": "Miller",
    "dateOfBirth": "1993-11-07",
    "gender": "Female",
    "phone": "555-186-7919",
    "email": "sarah.miller@example.com",
    "emergencyContactName": "Marcus Miller",
    "emergencyContactPhone": "555-404-5711",
    "insuranceProvider": "Blue Cross Blue Shield",
    "status": "ACTIVE",
    "assignedTherapistId": 4,
    "intakeDate": "2025-05-16",
    "isMinor": false,
    "presentingConcerns": "Client reports symptoms related to post-traumatic stress disorder, unspecified. Also experiencing difficulties sleeping and concentrating.",
    "diagnosisPrimary": "F43.10",
    "diagnosisSecondary": null
  },
  {
    "id": 116,
    "clientNumber": "MC-2024-08-016",
    "firstName": "Ava",
    "lastName": "Lopez",
    "dateOfBirth": "1982-08-29",
    "gender": "Female",
    "phone": "555-372-2301",
    "email": "ava.lopez@example.com",
    "emergencyContactName": "James Lopez",
    "emergencyContactPhone": "555-747-7738",
    "insuranceProvider": "Self-Pay",
    "status": "ACTIVE",
    "assignedTherapistId": 4,
    "intakeDate": "2024-08-15",
    "isMinor": false,
    "presentingConcerns": "Client reports symptoms related to attention-deficit hyperactivity disorder, predominantly inattentive type. ",
    "diagnosisPrimary": "F90.0",
    "diagnosisSecondary": null
  },
  {
    "id": 117,
    "clientNumber": "MC-2024-11-017",
    "firstName": "Sophia",
    "lastName": "Davis",
    "dateOfBirth": "1964-10-24",
    "gender": "Female",
    "phone": "555-938-4486",
    "email": "sophia.davis@example.com",
    "emergencyContactName": "Joseph Davis",
    "emergencyContactPhone": "555-851-6827",
    "insuranceProvider": "Kaiser Permanente",
    "status": "TRANSFERRED",
    "assignedTherapistId": 3,
    "intakeDate": "2024-11-05",
    "isMinor": false,
    "presentingConcerns": "Client reports symptoms related to major depressive disorder, single episode, moderate. ",
    "diagnosisPrimary": "F32.1",
    "diagnosisSecondary": "F31.32"
  },
  {
    "id": 118,
    "clientNumber": "MC-2025-04-018",
    "firstName": "Jessica",
    "lastName": "Lopez",
    "dateOfBirth": "1953-11-15",
    "gender": "Female",
    "phone": "555-961-8887",
    "email": "jessica.lopez@example.com",
    "emergencyContactName": "Thomas Lopez",
    "emergencyContactPhone": "555-989-9975",
    "insuranceProvider": "UnitedHealthcare",
    "status": "ACTIVE",
    "assignedTherapistId": 4,
    "intakeDate": "2025-04-04",
    "isMinor": false,
    "presentingConcerns": "Client reports symptoms related to bipolar disorder, current episode depressed, moderate. ",
    "diagnosisPrimary": "F31.32",
    "diagnosisSecondary": null
  },
  {
    "id": 119,
    "clientNumber": "MC-2023-07-019",
    "firstName": "William",
    "lastName": "Wilson",
    "dateOfBirth": "1999-06-12",
    "gender": "Male",
    "phone": "555-870-6814",
    "email": "william.wilson@example.com",
    "emergencyContactName": "James Wilson",
    "emergencyContactPhone": "555-425-9961",
    "insuranceProvider": "Kaiser Permanente",
    "status": "ACTIVE",
    "assignedTherapistId": 4,
    "intakeDate": "2023-07-23",
    "isMinor": false,
    "presentingConcerns": "Client reports symptoms related to post-traumatic stress disorder, unspecified. ",
    "diagnosisPrimary": "F43.10",
    "diagnosisSecondary": "F90.0"
  },
  {
    "id": 120,
    "clientNumber": "MC-2023-08-020",
    "firstName": "Robert",
    "lastName": "Wilson",
    "dateOfBirth": "1963-11-13",
    "gender": "Male",
    "phone": "555-714-1972",
    "email": "robert.wilson@example.com",
    "emergencyContactName": "Marcus Wilson",
    "emergencyContactPhone": "555-253-3108",
    "insuranceProvider": "UnitedHealthcare",
    "status": "ACTIVE",
    "assignedTherapistId": 3,
    "intakeDate": "2023-08-31",
    "isMinor": false,
    "presentingConcerns": "Client reports symptoms related to major depressive disorder, single episode, moderate. Also experiencing difficulties sleeping and concentrating.",
    "diagnosisPrimary": "F32.1",
    "diagnosisSecondary": null
  },
  {
    "id": 121,
    "clientNumber": "MC-2024-10-021",
    "firstName": "James",
    "lastName": "Brown",
    "dateOfBirth": "1951-08-30",
    "gender": "Male",
    "phone": "555-839-4229",
    "email": "james.brown@example.com",
    "emergencyContactName": "Morgan Brown",
    "emergencyContactPhone": "555-289-4368",
    "insuranceProvider": "Medicare",
    "status": "ACTIVE",
    "assignedTherapistId": 4,
    "intakeDate": "2024-10-03",
    "isMinor": false,
    "presentingConcerns": "Client reports symptoms related to obsessive-compulsive disorder, mixed obsessional thoughts and acts. ",
    "diagnosisPrimary": "F42.2",
    "diagnosisSecondary": null
  },
  {
    "id": 122,
    "clientNumber": "MC-2024-08-022",
    "firstName": "Susan",
    "lastName": "Anderson",
    "dateOfBirth": "1974-02-18",
    "gender": "Female",
    "phone": "555-260-6079",
    "email": "susan.anderson@example.com",
    "emergencyContactName": "Morgan Anderson",
    "emergencyContactPhone": "555-785-3320",
    "insuranceProvider": "Medicare",
    "status": "ACTIVE",
    "assignedTherapistId": 3,
    "intakeDate": "2024-08-20",
    "isMinor": false,
    "presentingConcerns": "Client reports symptoms related to obsessive-compulsive disorder, mixed obsessional thoughts and acts. ",
    "diagnosisPrimary": "F42.2",
    "diagnosisSecondary": null
  },
  {
    "id": 123,
    "clientNumber": "MC-2024-08-023",
    "firstName": "Jessica",
    "lastName": "Jones",
    "dateOfBirth": "1989-02-21",
    "gender": "Female",
    "phone": "555-221-8188",
    "email": "jessica.jones@example.com",
    "emergencyContactName": "Charles Jones",
    "emergencyContactPhone": "555-407-4730",
    "insuranceProvider": "Kaiser Permanente",
    "status": "ACTIVE",
    "assignedTherapistId": 3,
    "intakeDate": "2024-08-31",
    "isMinor": false,
    "presentingConcerns": "Client reports symptoms related to major depressive disorder, single episode, moderate. Also experiencing difficulties sleeping and concentrating.",
    "diagnosisPrimary": "F32.1",
    "diagnosisSecondary": "F43.22"
  },
  {
    "id": 124,
    "clientNumber": "MC-2025-01-024",
    "firstName": "Morgan",
    "lastName": "Rodriguez",
    "dateOfBirth": "1992-10-02",
    "gender": "Male",
    "phone": "555-566-4131",
    "email": "morgan.rodriguez@example.com",
    "emergencyContactName": "Jordan Rodriguez",
    "emergencyContactPhone": "555-822-4017",
    "insuranceProvider": "Medicare",
    "status": "INACTIVE",
    "assignedTherapistId": 3,
    "intakeDate": "2025-01-23",
    "isMinor": false,
    "presentingConcerns": "Client reports symptoms related to major depressive disorder, single episode, moderate. ",
    "diagnosisPrimary": "F32.1",
    "diagnosisSecondary": "F41.1"
  },
  {
    "id": 125,
    "clientNumber": "MC-2024-04-025",
    "firstName": "John",
    "lastName": "Williams",
    "dateOfBirth": "1951-08-16",
    "gender": "Male",
    "phone": "555-325-1515",
    "email": "john.williams@example.com",
    "emergencyContactName": "Jordan Williams",
    "emergencyContactPhone": "555-887-3820",
    "insuranceProvider": "Self-Pay",
    "status": "WAITLIST",
    "assignedTherapistId": null,
    "intakeDate": "2024-04-07",
    "isMinor": false,
    "presentingConcerns": "Client reports symptoms related to obsessive-compulsive disorder, mixed obsessional thoughts and acts. Also experiencing difficulties sleeping and concentrating.",
    "diagnosisPrimary": "F42.2",
    "diagnosisSecondary": null
  }
];

// Appointments
export const mockAppointments = [
  {
    "id": 1001,
    "clientId": 118,
    "therapistId": 4,
    "appointmentDate": "2025-07-14",
    "startTime": "11:00",
    "duration": 45,
    "sessionType": "Couples",
    "modality": "Phone",
    "status": "SCHEDULED",
    "cptCode": "90837"
  },
  {
    "id": 1002,
    "clientId": 111,
    "therapistId": 2,
    "appointmentDate": "2025-06-08",
    "startTime": "12:00",
    "duration": 45,
    "sessionType": "Individual",
    "modality": "Telehealth",
    "status": "COMPLETED",
    "cptCode": "90834",
    "telehealthLink": "https://telehealth.mindcare.com/room/1002"
  },
  {
    "id": 1003,
    "clientId": 116,
    "therapistId": 4,
    "appointmentDate": "2025-06-08",
    "startTime": "16:00",
    "duration": 60,
    "sessionType": "Group",
    "modality": "In-Person",
    "status": "CANCELLED",
    "cptCode": "90853"
  },
  {
    "id": 1004,
    "clientId": 110,
    "therapistId": 4,
    "appointmentDate": "2025-06-29",
    "startTime": "16:00",
    "duration": 60,
    "sessionType": "Group",
    "modality": "Phone",
    "status": "CANCELLED",
    "cptCode": "90834"
  },
  {
    "id": 1005,
    "clientId": 122,
    "therapistId": 3,
    "appointmentDate": "2025-07-23",
    "startTime": "12:00",
    "duration": 60,
    "sessionType": "Group",
    "modality": "In-Person",
    "status": "SCHEDULED",
    "cptCode": "90834"
  },
  {
    "id": 1006,
    "clientId": 113,
    "therapistId": 4,
    "appointmentDate": "2025-07-16",
    "startTime": "12:00",
    "duration": 60,
    "sessionType": "Family",
    "modality": "Telehealth",
    "status": "SCHEDULED",
    "cptCode": "90834",
    "telehealthLink": "https://telehealth.mindcare.com/room/1006"
  },
  {
    "id": 1007,
    "clientId": 121,
    "therapistId": 4,
    "appointmentDate": "2025-06-18",
    "startTime": "16:00",
    "duration": 45,
    "sessionType": "Individual",
    "modality": "Telehealth",
    "status": "SCHEDULED",
    "cptCode": "90834",
    "telehealthLink": "https://telehealth.mindcare.com/room/1007"
  },
  {
    "id": 1008,
    "clientId": 110,
    "therapistId": 4,
    "appointmentDate": "2025-07-24",
    "startTime": "09:00",
    "duration": 60,
    "sessionType": "Individual",
    "modality": "Telehealth",
    "status": "SCHEDULED",
    "cptCode": "90847",
    "telehealthLink": "https://telehealth.mindcare.com/room/1008"
  },
  {
    "id": 1009,
    "clientId": 105,
    "therapistId": 2,
    "appointmentDate": "2025-06-30",
    "startTime": "16:00",
    "duration": 60,
    "sessionType": "Family",
    "modality": "Telehealth",
    "status": "NO_SHOW",
    "cptCode": "90837",
    "telehealthLink": "https://telehealth.mindcare.com/room/1009"
  },
  {
    "id": 1010,
    "clientId": 118,
    "therapistId": 4,
    "appointmentDate": "2025-06-17",
    "startTime": "11:00",
    "duration": 45,
    "sessionType": "Couples",
    "modality": "In-Person",
    "status": "SCHEDULED",
    "cptCode": "90847"
  },
  {
    "id": 1011,
    "clientId": 111,
    "therapistId": 2,
    "appointmentDate": "2025-06-06",
    "startTime": "16:00",
    "duration": 45,
    "sessionType": "Individual",
    "modality": "Telehealth",
    "status": "SCHEDULED",
    "cptCode": "90853",
    "telehealthLink": "https://telehealth.mindcare.com/room/1011"
  },
  {
    "id": 1012,
    "clientId": 107,
    "therapistId": 2,
    "appointmentDate": "2025-06-17",
    "startTime": "16:00",
    "duration": 45,
    "sessionType": "Couples",
    "modality": "Phone",
    "status": "COMPLETED",
    "cptCode": "90837"
  },
  {
    "id": 1013,
    "clientId": 107,
    "therapistId": 2,
    "appointmentDate": "2025-06-22",
    "startTime": "15:00",
    "duration": 60,
    "sessionType": "Individual",
    "modality": "Telehealth",
    "status": "CANCELLED",
    "cptCode": "90837",
    "telehealthLink": "https://telehealth.mindcare.com/room/1013"
  },
  {
    "id": 1014,
    "clientId": 110,
    "therapistId": 4,
    "appointmentDate": "2025-06-09",
    "startTime": "11:00",
    "duration": 60,
    "sessionType": "Individual",
    "modality": "Phone",
    "status": "COMPLETED",
    "cptCode": "90834"
  },
  {
    "id": 1015,
    "clientId": 123,
    "therapistId": 3,
    "appointmentDate": "2025-06-18",
    "startTime": "15:00",
    "duration": 60,
    "sessionType": "Group",
    "modality": "Phone",
    "status": "CANCELLED",
    "cptCode": "90853"
  },
  {
    "id": 1016,
    "clientId": 120,
    "therapistId": 3,
    "appointmentDate": "2025-07-08",
    "startTime": "09:00",
    "duration": 45,
    "sessionType": "Individual",
    "modality": "Telehealth",
    "status": "COMPLETED",
    "cptCode": "90853",
    "telehealthLink": "https://telehealth.mindcare.com/room/1016"
  },
  {
    "id": 1017,
    "clientId": 103,
    "therapistId": 2,
    "appointmentDate": "2025-06-07",
    "startTime": "10:00",
    "duration": 60,
    "sessionType": "Couples",
    "modality": "In-Person",
    "status": "COMPLETED",
    "cptCode": "90837"
  },
  {
    "id": 1018,
    "clientId": 115,
    "therapistId": 4,
    "appointmentDate": "2025-06-18",
    "startTime": "14:00",
    "duration": 60,
    "sessionType": "Family",
    "modality": "Phone",
    "status": "COMPLETED",
    "cptCode": "90837"
  },
  {
    "id": 1019,
    "clientId": 122,
    "therapistId": 3,
    "appointmentDate": "2025-07-02",
    "startTime": "14:00",
    "duration": 45,
    "sessionType": "Individual",
    "modality": "Phone",
    "status": "COMPLETED",
    "cptCode": "90834"
  },
  {
    "id": 1020,
    "clientId": 123,
    "therapistId": 3,
    "appointmentDate": "2025-07-26",
    "startTime": "11:00",
    "duration": 45,
    "sessionType": "Family",
    "modality": "In-Person",
    "status": "SCHEDULED",
    "cptCode": "90837"
  },
  {
    "id": 1021,
    "clientId": 103,
    "therapistId": 2,
    "appointmentDate": "2025-06-08",
    "startTime": "13:00",
    "duration": 60,
    "sessionType": "Individual",
    "modality": "Phone",
    "status": "COMPLETED",
    "cptCode": "90837"
  },
  {
    "id": 1022,
    "clientId": 104,
    "therapistId": 4,
    "appointmentDate": "2025-07-03",
    "startTime": "09:00",
    "duration": 60,
    "sessionType": "Family",
    "modality": "Telehealth",
    "status": "SCHEDULED",
    "cptCode": "90834",
    "telehealthLink": "https://telehealth.mindcare.com/room/1022"
  },
  {
    "id": 1023,
    "clientId": 105,
    "therapistId": 2,
    "appointmentDate": "2025-07-03",
    "startTime": "14:00",
    "duration": 60,
    "sessionType": "Couples",
    "modality": "Telehealth",
    "status": "SCHEDULED",
    "cptCode": "90853",
    "telehealthLink": "https://telehealth.mindcare.com/room/1023"
  },
  {
    "id": 1024,
    "clientId": 111,
    "therapistId": 2,
    "appointmentDate": "2025-07-05",
    "startTime": "10:00",
    "duration": 60,
    "sessionType": "Group",
    "modality": "Phone",
    "status": "COMPLETED",
    "cptCode": "90837"
  },
  {
    "id": 1025,
    "clientId": 121,
    "therapistId": 4,
    "appointmentDate": "2025-06-20",
    "startTime": "16:00",
    "duration": 60,
    "sessionType": "Couples",
    "modality": "In-Person",
    "status": "COMPLETED",
    "cptCode": "90834"
  },
  {
    "id": 1026,
    "clientId": 120,
    "therapistId": 3,
    "appointmentDate": "2025-06-08",
    "startTime": "10:00",
    "duration": 45,
    "sessionType": "Group",
    "modality": "Phone",
    "status": "COMPLETED",
    "cptCode": "90834"
  },
  {
    "id": 1027,
    "clientId": 111,
    "therapistId": 2,
    "appointmentDate": "2025-06-23",
    "startTime": "14:00",
    "duration": 45,
    "sessionType": "Individual",
    "modality": "Telehealth",
    "status": "NO_SHOW",
    "cptCode": "90837",
    "telehealthLink": "https://telehealth.mindcare.com/room/1027"
  },
  {
    "id": 1028,
    "clientId": 116,
    "therapistId": 4,
    "appointmentDate": "2025-07-15",
    "startTime": "12:00",
    "duration": 45,
    "sessionType": "Group",
    "modality": "Telehealth",
    "status": "SCHEDULED",
    "cptCode": "90837",
    "telehealthLink": "https://telehealth.mindcare.com/room/1028"
  },
  {
    "id": 1029,
    "clientId": 107,
    "therapistId": 2,
    "appointmentDate": "2025-07-03",
    "startTime": "11:00",
    "duration": 45,
    "sessionType": "Group",
    "modality": "Telehealth",
    "status": "COMPLETED",
    "cptCode": "90847",
    "telehealthLink": "https://telehealth.mindcare.com/room/1029"
  },
  {
    "id": 1030,
    "clientId": 115,
    "therapistId": 4,
    "appointmentDate": "2025-06-16",
    "startTime": "09:00",
    "duration": 45,
    "sessionType": "Group",
    "modality": "Phone",
    "status": "CANCELLED",
    "cptCode": "90847"
  },
  {
    "id": 1031,
    "clientId": 122,
    "therapistId": 3,
    "appointmentDate": "2025-06-23",
    "startTime": "15:00",
    "duration": 45,
    "sessionType": "Group",
    "modality": "Phone",
    "status": "COMPLETED",
    "cptCode": "90853"
  },
  {
    "id": 1032,
    "clientId": 110,
    "therapistId": 4,
    "appointmentDate": "2025-06-06",
    "startTime": "09:00",
    "duration": 45,
    "sessionType": "Group",
    "modality": "Telehealth",
    "status": "SCHEDULED",
    "cptCode": "90853",
    "telehealthLink": "https://telehealth.mindcare.com/room/1032"
  },
  {
    "id": 1033,
    "clientId": 104,
    "therapistId": 4,
    "appointmentDate": "2025-07-07",
    "startTime": "12:00",
    "duration": 45,
    "sessionType": "Group",
    "modality": "Phone",
    "status": "SCHEDULED",
    "cptCode": "90837"
  },
  {
    "id": 1034,
    "clientId": 104,
    "therapistId": 4,
    "appointmentDate": "2025-07-15",
    "startTime": "12:00",
    "duration": 45,
    "sessionType": "Individual",
    "modality": "Telehealth",
    "status": "SCHEDULED",
    "cptCode": "90837",
    "telehealthLink": "https://telehealth.mindcare.com/room/1034"
  },
  {
    "id": 1035,
    "clientId": 116,
    "therapistId": 4,
    "appointmentDate": "2025-07-07",
    "startTime": "11:00",
    "duration": 45,
    "sessionType": "Group",
    "modality": "In-Person",
    "status": "CANCELLED",
    "cptCode": "90853"
  },
  {
    "id": 1036,
    "clientId": 121,
    "therapistId": 4,
    "appointmentDate": "2025-06-11",
    "startTime": "11:00",
    "duration": 45,
    "sessionType": "Individual",
    "modality": "In-Person",
    "status": "COMPLETED",
    "cptCode": "90837"
  },
  {
    "id": 1037,
    "clientId": 119,
    "therapistId": 4,
    "appointmentDate": "2025-07-27",
    "startTime": "09:00",
    "duration": 45,
    "sessionType": "Family",
    "modality": "Phone",
    "status": "SCHEDULED",
    "cptCode": "90847"
  },
  {
    "id": 1038,
    "clientId": 115,
    "therapistId": 4,
    "appointmentDate": "2025-07-20",
    "startTime": "16:00",
    "duration": 45,
    "sessionType": "Family",
    "modality": "Telehealth",
    "status": "SCHEDULED",
    "cptCode": "90853",
    "telehealthLink": "https://telehealth.mindcare.com/room/1038"
  },
  {
    "id": 1039,
    "clientId": 116,
    "therapistId": 4,
    "appointmentDate": "2025-07-16",
    "startTime": "09:00",
    "duration": 45,
    "sessionType": "Family",
    "modality": "In-Person",
    "status": "SCHEDULED",
    "cptCode": "90837"
  },
  {
    "id": 1040,
    "clientId": 104,
    "therapistId": 4,
    "appointmentDate": "2025-06-11",
    "startTime": "10:00",
    "duration": 45,
    "sessionType": "Individual",
    "modality": "Telehealth",
    "status": "COMPLETED",
    "cptCode": "90837",
    "telehealthLink": "https://telehealth.mindcare.com/room/1040"
  },
  {
    "id": 1041,
    "clientId": 107,
    "therapistId": 2,
    "appointmentDate": "2025-07-09",
    "startTime": "10:00",
    "duration": 45,
    "sessionType": "Family",
    "modality": "Phone",
    "status": "NO_SHOW",
    "cptCode": "90837"
  },
  {
    "id": 1042,
    "clientId": 110,
    "therapistId": 4,
    "appointmentDate": "2025-07-26",
    "startTime": "14:00",
    "duration": 60,
    "sessionType": "Couples",
    "modality": "In-Person",
    "status": "SCHEDULED",
    "cptCode": "90853"
  },
  {
    "id": 1043,
    "clientId": 123,
    "therapistId": 3,
    "appointmentDate": "2025-06-27",
    "startTime": "09:00",
    "duration": 60,
    "sessionType": "Family",
    "modality": "Phone",
    "status": "COMPLETED",
    "cptCode": "90834"
  },
  {
    "id": 1044,
    "clientId": 115,
    "therapistId": 4,
    "appointmentDate": "2025-06-11",
    "startTime": "12:00",
    "duration": 45,
    "sessionType": "Family",
    "modality": "Telehealth",
    "status": "SCHEDULED",
    "cptCode": "90834",
    "telehealthLink": "https://telehealth.mindcare.com/room/1044"
  },
  {
    "id": 1045,
    "clientId": 118,
    "therapistId": 4,
    "appointmentDate": "2025-07-27",
    "startTime": "16:00",
    "duration": 45,
    "sessionType": "Individual",
    "modality": "Phone",
    "status": "SCHEDULED",
    "cptCode": "90834"
  },
  {
    "id": 1046,
    "clientId": 103,
    "therapistId": 2,
    "appointmentDate": "2025-06-18",
    "startTime": "11:00",
    "duration": 60,
    "sessionType": "Group",
    "modality": "In-Person",
    "status": "COMPLETED",
    "cptCode": "90834"
  },
  {
    "id": 1047,
    "clientId": 107,
    "therapistId": 2,
    "appointmentDate": "2025-07-12",
    "startTime": "12:00",
    "duration": 60,
    "sessionType": "Group",
    "modality": "Phone",
    "status": "SCHEDULED",
    "cptCode": "90847"
  },
  {
    "id": 1048,
    "clientId": 123,
    "therapistId": 3,
    "appointmentDate": "2025-07-14",
    "startTime": "12:00",
    "duration": 60,
    "sessionType": "Family",
    "modality": "Telehealth",
    "status": "SCHEDULED",
    "cptCode": "90853",
    "telehealthLink": "https://telehealth.mindcare.com/room/1048"
  },
  {
    "id": 1049,
    "clientId": 118,
    "therapistId": 4,
    "appointmentDate": "2025-06-17",
    "startTime": "16:00",
    "duration": 45,
    "sessionType": "Family",
    "modality": "In-Person",
    "status": "COMPLETED",
    "cptCode": "90834"
  },
  {
    "id": 1050,
    "clientId": 116,
    "therapistId": 4,
    "appointmentDate": "2025-06-30",
    "startTime": "13:00",
    "duration": 45,
    "sessionType": "Individual",
    "modality": "Telehealth",
    "status": "COMPLETED",
    "cptCode": "90853",
    "telehealthLink": "https://telehealth.mindcare.com/room/1050"
  }
];

// Session Notes
export const mockSessionNotes = [
  {
    "id": 5001,
    "appointmentId": 1002,
    "clientId": 111,
    "therapistId": 2,
    "noteFormat": "BIRP",
    "noteContent": "Behavior: Client engaged well, maintained eye contact, affect was mood-congruent.\nIntervention: Explored cognitive distortions around workplace value. Challenged catastrophizing thoughts.\nResponse: Client was able to identify alternative thoughts but struggled to believe them emotionally.\nPlan: Assign thought record worksheet for homework.",
    "diagnosisPrimary": "F90.0",
    "cptCode": "90834",
    "sessionDurationMinutes": 45,
    "isLate": false,
    "supervisorId": null,
    "supervisorSignedAt": null,
    "createdAt": "2025-06-08T00:00:00"
  },
  {
    "id": 5002,
    "appointmentId": 1012,
    "clientId": 107,
    "therapistId": 2,
    "noteFormat": "SOAP",
    "noteContent": "Subjective: Client reports feeling highly anxious this week. 'I feel like I can't breathe when I think about it.'\nObjective: Client appeared restless, fidgeting with hands. Speech was rapid but coherent.\nAssessment: Client continues to struggle with generalized anxiety. Insight is good. Risk assessment: No SI/HI.\nPlan: Practiced square breathing. Client will use this technique twice daily. Next session scheduled for next week.",
    "diagnosisPrimary": "F43.10",
    "cptCode": "90837",
    "sessionDurationMinutes": 45,
    "isLate": false,
    "supervisorId": null,
    "supervisorSignedAt": null,
    "createdAt": "2025-06-17T00:00:00"
  },
  {
    "id": 5003,
    "appointmentId": 1014,
    "clientId": 110,
    "therapistId": 4,
    "noteFormat": "DAP",
    "noteContent": "Data: Client arrived on time. Discussed ongoing depressive symptoms. Sleep has improved slightly (6 hrs/night). Mood remains low.\nAssessment: Client making slow progress. Behavioral activation strategies are partially successful. Depression is moderate.\nPlan: Continue CBT for cognitive restructuring. Client agreed to schedule one social activity this weekend.",
    "diagnosisPrimary": "F43.10",
    "cptCode": "90834",
    "sessionDurationMinutes": 60,
    "isLate": false,
    "supervisorId": null,
    "supervisorSignedAt": null,
    "createdAt": "2025-06-09T00:00:00"
  },
  {
    "id": 5004,
    "appointmentId": 1016,
    "clientId": 120,
    "therapistId": 3,
    "noteFormat": "DAP",
    "noteContent": "Data: Client arrived on time. Discussed ongoing depressive symptoms. Sleep has improved slightly (6 hrs/night). Mood remains low.\nAssessment: Client making slow progress. Behavioral activation strategies are partially successful. Depression is moderate.\nPlan: Continue CBT for cognitive restructuring. Client agreed to schedule one social activity this weekend.",
    "diagnosisPrimary": "F32.1",
    "cptCode": "90853",
    "sessionDurationMinutes": 45,
    "isLate": false,
    "supervisorId": null,
    "supervisorSignedAt": null,
    "createdAt": "2025-07-08T00:00:00"
  },
  {
    "id": 5005,
    "appointmentId": 1017,
    "clientId": 103,
    "therapistId": 2,
    "noteFormat": "SOAP",
    "noteContent": "Subjective: Client reports feeling highly anxious this week. 'I feel like I can't breathe when I think about it.'\nObjective: Client appeared restless, fidgeting with hands. Speech was rapid but coherent.\nAssessment: Client continues to struggle with generalized anxiety. Insight is good. Risk assessment: No SI/HI.\nPlan: Practiced square breathing. Client will use this technique twice daily. Next session scheduled for next week.",
    "diagnosisPrimary": "F31.32",
    "cptCode": "90837",
    "sessionDurationMinutes": 60,
    "isLate": false,
    "supervisorId": null,
    "supervisorSignedAt": null,
    "createdAt": "2025-06-07T00:00:00"
  },
  {
    "id": 5006,
    "appointmentId": 1018,
    "clientId": 115,
    "therapistId": 4,
    "noteFormat": "DAP",
    "noteContent": "Data: Client arrived on time. Discussed ongoing depressive symptoms. Sleep has improved slightly (6 hrs/night). Mood remains low.\nAssessment: Client making slow progress. Behavioral activation strategies are partially successful. Depression is moderate.\nPlan: Continue CBT for cognitive restructuring. Client agreed to schedule one social activity this weekend.",
    "diagnosisPrimary": "F43.10",
    "cptCode": "90837",
    "sessionDurationMinutes": 60,
    "isLate": false,
    "supervisorId": null,
    "supervisorSignedAt": null,
    "createdAt": "2025-06-18T00:00:00"
  },
  {
    "id": 5007,
    "appointmentId": 1019,
    "clientId": 122,
    "therapistId": 3,
    "noteFormat": "BIRP",
    "noteContent": "Behavior: Client engaged well, maintained eye contact, affect was mood-congruent.\nIntervention: Explored cognitive distortions around workplace value. Challenged catastrophizing thoughts.\nResponse: Client was able to identify alternative thoughts but struggled to believe them emotionally.\nPlan: Assign thought record worksheet for homework.",
    "diagnosisPrimary": "F42.2",
    "cptCode": "90834",
    "sessionDurationMinutes": 45,
    "isLate": false,
    "supervisorId": null,
    "supervisorSignedAt": null,
    "createdAt": "2025-07-02T00:00:00"
  },
  {
    "id": 5008,
    "appointmentId": 1021,
    "clientId": 103,
    "therapistId": 2,
    "noteFormat": "BIRP",
    "noteContent": "Behavior: Client engaged well, maintained eye contact, affect was mood-congruent.\nIntervention: Explored cognitive distortions around workplace value. Challenged catastrophizing thoughts.\nResponse: Client was able to identify alternative thoughts but struggled to believe them emotionally.\nPlan: Assign thought record worksheet for homework.",
    "diagnosisPrimary": "F31.32",
    "cptCode": "90837",
    "sessionDurationMinutes": 60,
    "isLate": false,
    "supervisorId": null,
    "supervisorSignedAt": null,
    "createdAt": "2025-06-08T00:00:00"
  },
  {
    "id": 5009,
    "appointmentId": 1024,
    "clientId": 111,
    "therapistId": 2,
    "noteFormat": "DAP",
    "noteContent": "Data: Client arrived on time. Discussed ongoing depressive symptoms. Sleep has improved slightly (6 hrs/night). Mood remains low.\nAssessment: Client making slow progress. Behavioral activation strategies are partially successful. Depression is moderate.\nPlan: Continue CBT for cognitive restructuring. Client agreed to schedule one social activity this weekend.",
    "diagnosisPrimary": "F90.0",
    "cptCode": "90837",
    "sessionDurationMinutes": 60,
    "isLate": false,
    "supervisorId": null,
    "supervisorSignedAt": null,
    "createdAt": "2025-07-05T00:00:00"
  },
  {
    "id": 5010,
    "appointmentId": 1025,
    "clientId": 121,
    "therapistId": 4,
    "noteFormat": "SOAP",
    "noteContent": "Subjective: Client reports feeling highly anxious this week. 'I feel like I can't breathe when I think about it.'\nObjective: Client appeared restless, fidgeting with hands. Speech was rapid but coherent.\nAssessment: Client continues to struggle with generalized anxiety. Insight is good. Risk assessment: No SI/HI.\nPlan: Practiced square breathing. Client will use this technique twice daily. Next session scheduled for next week.",
    "diagnosisPrimary": "F42.2",
    "cptCode": "90834",
    "sessionDurationMinutes": 60,
    "isLate": true,
    "supervisorId": null,
    "supervisorSignedAt": null,
    "createdAt": "2025-06-22T00:00:00"
  },
  {
    "id": 5011,
    "appointmentId": 1026,
    "clientId": 120,
    "therapistId": 3,
    "noteFormat": "DAP",
    "noteContent": "Data: Client arrived on time. Discussed ongoing depressive symptoms. Sleep has improved slightly (6 hrs/night). Mood remains low.\nAssessment: Client making slow progress. Behavioral activation strategies are partially successful. Depression is moderate.\nPlan: Continue CBT for cognitive restructuring. Client agreed to schedule one social activity this weekend.",
    "diagnosisPrimary": "F32.1",
    "cptCode": "90834",
    "sessionDurationMinutes": 45,
    "isLate": false,
    "supervisorId": null,
    "supervisorSignedAt": null,
    "createdAt": "2025-06-08T00:00:00"
  },
  {
    "id": 5012,
    "appointmentId": 1029,
    "clientId": 107,
    "therapistId": 2,
    "noteFormat": "BIRP",
    "noteContent": "Behavior: Client engaged well, maintained eye contact, affect was mood-congruent.\nIntervention: Explored cognitive distortions around workplace value. Challenged catastrophizing thoughts.\nResponse: Client was able to identify alternative thoughts but struggled to believe them emotionally.\nPlan: Assign thought record worksheet for homework.",
    "diagnosisPrimary": "F43.10",
    "cptCode": "90847",
    "sessionDurationMinutes": 45,
    "isLate": false,
    "supervisorId": null,
    "supervisorSignedAt": null,
    "createdAt": "2025-07-03T00:00:00"
  },
  {
    "id": 5013,
    "appointmentId": 1031,
    "clientId": 122,
    "therapistId": 3,
    "noteFormat": "BIRP",
    "noteContent": "Behavior: Client engaged well, maintained eye contact, affect was mood-congruent.\nIntervention: Explored cognitive distortions around workplace value. Challenged catastrophizing thoughts.\nResponse: Client was able to identify alternative thoughts but struggled to believe them emotionally.\nPlan: Assign thought record worksheet for homework.",
    "diagnosisPrimary": "F42.2",
    "cptCode": "90853",
    "sessionDurationMinutes": 45,
    "isLate": false,
    "supervisorId": null,
    "supervisorSignedAt": null,
    "createdAt": "2025-06-23T00:00:00"
  },
  {
    "id": 5014,
    "appointmentId": 1036,
    "clientId": 121,
    "therapistId": 4,
    "noteFormat": "DAP",
    "noteContent": "Data: Client arrived on time. Discussed ongoing depressive symptoms. Sleep has improved slightly (6 hrs/night). Mood remains low.\nAssessment: Client making slow progress. Behavioral activation strategies are partially successful. Depression is moderate.\nPlan: Continue CBT for cognitive restructuring. Client agreed to schedule one social activity this weekend.",
    "diagnosisPrimary": "F42.2",
    "cptCode": "90837",
    "sessionDurationMinutes": 45,
    "isLate": false,
    "supervisorId": 5,
    "supervisorSignedAt": "2026-07-10T12:46:46",
    "createdAt": "2025-06-11T00:00:00"
  },
  {
    "id": 5015,
    "appointmentId": 1040,
    "clientId": 104,
    "therapistId": 4,
    "noteFormat": "DAP",
    "noteContent": "Data: Client arrived on time. Discussed ongoing depressive symptoms. Sleep has improved slightly (6 hrs/night). Mood remains low.\nAssessment: Client making slow progress. Behavioral activation strategies are partially successful. Depression is moderate.\nPlan: Continue CBT for cognitive restructuring. Client agreed to schedule one social activity this weekend.",
    "diagnosisPrimary": "F43.10",
    "cptCode": "90837",
    "sessionDurationMinutes": 45,
    "isLate": false,
    "supervisorId": 5,
    "supervisorSignedAt": "2026-07-10T12:46:46",
    "createdAt": "2025-06-11T00:00:00"
  },
  {
    "id": 5016,
    "appointmentId": 1043,
    "clientId": 123,
    "therapistId": 3,
    "noteFormat": "SOAP",
    "noteContent": "Subjective: Client reports feeling highly anxious this week. 'I feel like I can't breathe when I think about it.'\nObjective: Client appeared restless, fidgeting with hands. Speech was rapid but coherent.\nAssessment: Client continues to struggle with generalized anxiety. Insight is good. Risk assessment: No SI/HI.\nPlan: Practiced square breathing. Client will use this technique twice daily. Next session scheduled for next week.",
    "diagnosisPrimary": "F32.1",
    "cptCode": "90834",
    "sessionDurationMinutes": 60,
    "isLate": false,
    "supervisorId": null,
    "supervisorSignedAt": null,
    "createdAt": "2025-06-27T00:00:00"
  },
  {
    "id": 5017,
    "appointmentId": 1046,
    "clientId": 103,
    "therapistId": 2,
    "noteFormat": "BIRP",
    "noteContent": "Behavior: Client engaged well, maintained eye contact, affect was mood-congruent.\nIntervention: Explored cognitive distortions around workplace value. Challenged catastrophizing thoughts.\nResponse: Client was able to identify alternative thoughts but struggled to believe them emotionally.\nPlan: Assign thought record worksheet for homework.",
    "diagnosisPrimary": "F31.32",
    "cptCode": "90834",
    "sessionDurationMinutes": 60,
    "isLate": true,
    "supervisorId": null,
    "supervisorSignedAt": null,
    "createdAt": "2025-06-20T00:00:00"
  },
  {
    "id": 5018,
    "appointmentId": 1049,
    "clientId": 118,
    "therapistId": 4,
    "noteFormat": "BIRP",
    "noteContent": "Behavior: Client engaged well, maintained eye contact, affect was mood-congruent.\nIntervention: Explored cognitive distortions around workplace value. Challenged catastrophizing thoughts.\nResponse: Client was able to identify alternative thoughts but struggled to believe them emotionally.\nPlan: Assign thought record worksheet for homework.",
    "diagnosisPrimary": "F31.32",
    "cptCode": "90834",
    "sessionDurationMinutes": 45,
    "isLate": false,
    "supervisorId": 5,
    "supervisorSignedAt": "2026-07-10T12:46:46",
    "createdAt": "2025-06-17T00:00:00"
  },
  {
    "id": 5019,
    "appointmentId": 1050,
    "clientId": 116,
    "therapistId": 4,
    "noteFormat": "DAP",
    "noteContent": "Data: Client arrived on time. Discussed ongoing depressive symptoms. Sleep has improved slightly (6 hrs/night). Mood remains low.\nAssessment: Client making slow progress. Behavioral activation strategies are partially successful. Depression is moderate.\nPlan: Continue CBT for cognitive restructuring. Client agreed to schedule one social activity this weekend.",
    "diagnosisPrimary": "F90.0",
    "cptCode": "90853",
    "sessionDurationMinutes": 45,
    "isLate": false,
    "supervisorId": null,
    "supervisorSignedAt": null,
    "createdAt": "2025-06-30T00:00:00"
  }
];

export const mockTreatmentPlans = [];

export const mockCrisisAssessments = [];

export const mockSafetyPlans = [];

export const mockOutcomeMeasures = [];

export const mockBilling = [];

export const mockAuditLogs = [];

export const mockAnalytics = { monthlyRevenue: [], appointmentsByStatus: [], clientsByDiagnosis: [] };
